import type { Metadata } from "next";
import { Macondo } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import Link from "next/link";

const macondo = Macondo({
  weight: "400",
  preload: false,
});

export const metadata: Metadata = {
  title: "Welcome to Sugar DD",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={macondo.className} data-theme="luxury">
        <div className="drawer drawer-end">
          <input id="nav-drawer" type="checkbox" className="drawer-toggle" />
          <div className="drawer-content flex flex-col justify-between h-screen p-4">
            <Navbar />
            {children}
            <Footer />
          </div>
          <div className="md:hidden drawer-side">
            <label
              htmlFor="nav-drawer"
              aria-label="close sidebar"
              className="drawer-overlay"
            ></label>
            <ul className="menu p-4 w-48 min-h-full bg-base-200">
              <li>
                <Link href="/about-us">
                  <button className="btn btn-block">About Us</button>
                </Link>
              </li>
              <li>
                <Link href="/contact-us">
                  <button className="btn btn-block">Contact Us</button>
                </Link>
              </li>
              <li>
                <Link href="/faq">
                  <button className="btn btn-block">FAQs</button>
                </Link>
              </li>
              <li>
                <Link href="/track-order">
                  <button className="btn btn-primary">Track Order</button>
                </Link>
              </li>
            </ul>
          </div>
        </div>
      </body>
    </html>
  );
}
