import "./store-globals.css";

import Footer from "@/components/Footer";
import Link from "next/link";
import { LogoutLink } from "@kinde-oss/kinde-auth-nextjs/components";
import type { Metadata } from "next";
import Navbar from "@/components/Navbar";
import { Quicksand } from "next/font/google";
import UserAccountActions from "@/components/UserAccountActions";
import { getKindeServerSession } from "@kinde-oss/kinde-auth-nextjs/server";

const quicksand = Quicksand({
  subsets: ["latin"],
  preload: true,
});

export const metadata: Metadata = {
  title: "Welcome to Sugar DD",
  description: "Generated by create next app",
};

export default async function StoreLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const { isAuthenticated, getPermission } = getKindeServerSession();
  const isUserLoggedin = await isAuthenticated();
  const adminPermission = await getPermission("store:admin");

  return (
    <html lang="en">
      <body className={`${quicksand.className}`} data-theme="luxury">
        <div className="drawer drawer-end">
          <input id="nav-drawer" type="checkbox" className="drawer-toggle" />
          <div className="drawer-content flex flex-col justify-between h-screen p-4">
            <Navbar />
            {children}
            <Footer />
          </div>
          <div className="md:hidden drawer-side">
            <label
              htmlFor="nav-drawer"
              aria-label="close sidebar"
              className="drawer-overlay"
            ></label>
            <ul className="menu px-0 py-2 w-60 min-h-full bg-base-200">
              <li>
                <h1 className="text-xl font-bold">Sugar DD Store</h1>
              </li>
              <div className="divider"></div>
              <li>
                <UserAccountActions />
              </li>
              <li>
                <Link className="text-xl leading-10 my-2" href="/about-us">
                  About Us
                </Link>
              </li>
              <li>
                <Link className="text-xl leading-10 my-2" href="/faq">
                  FAQs
                </Link>
              </li>
              <li>
                <Link className="text-xl leading-10 my-2" href="/orders">
                  View Orders
                </Link>
              </li>
              {adminPermission?.isGranted && (
                <li>
                  <Link className="text-xl leading-10 my-2" href="/admin-dash">
                    Admin Dashboard
                  </Link>
                </li>
              )}
              {isUserLoggedin && (
                <li className="absolute bottom-2 w-full">
                  <div className="divider m-1"></div>
                  <LogoutLink className="ml-6">
                    <button>Log Out</button>
                  </LogoutLink>
                </li>
              )}
            </ul>
          </div>
        </div>
      </body>
    </html>
  );
}
